version: '3.9'

services:
  grpc:
    image: sudeeptirao/dafny_grpc:latest
    build:
      context: .
      #dockerfile: docker/Dockerfile
    # volumes:
    #   - ./src:/home/node/src:ro
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    command: /home/dafny-grpc-server/bazel-bin/src/server -d /home/dafny/Binaries/Dafny -j 1 -n /mnt/nfs #-nfs and then the file location of a docker image that runs NFS
    volumes:
      - nfs-data:/mnt/nfs
    #cap_add:
      #- SYS_ADMIN
    ports:
      - "50051:50051"
    networks:
      - swarm_net

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "50052:50052"
  #   deploy:
  #     mode: global  # Ensures it runs only on the manager node
  #    networks:
  #     - swarm_net
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    privileged: true
    environment:
      - SHARED_DIRECTORY=/exports
    volumes:
      - nfs-data:/exports
      #- /proc/fs/nfsd:/proc/fs/nfsd
    networks:
      - swarm_net
    ports:
      - "2049:2049"
  nginx:
    image: nginx:1.20.0
    container_name: nginx
    ports:
      - "50052:50052"
    depends_on: 
      - grpc
    #deploy:
    #  mode: replicated  # Ensures it runs only on the manager node
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - swarm_net
  cAdvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "3003:8080"

networks:
  swarm_net:
    driver: overlay


volumes:
  nfs-data: