# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verifier.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0everifier.proto\x12\x13\x44\x61\x66nyExecutorServer\"\x1a\n\tCreateDir\x12\r\n\x05owner\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x93\x01\n\x15\x43loneAndVerifyRequest\x12\x15\n\rdirectoryPath\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x15\n\rmodifyingFile\x18\x03 \x01(\t\x12>\n\x0crequestsList\x18\x04 \x03(\x0b\x32(.DafnyExecutorServer.VerificationRequest\"?\n\tTmpFolder\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x15\n\rmodifyingFile\x18\x02 \x01(\t\x12\r\n\x05owner\x18\x03 \x01(\t\"U\n\x13VerificationRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x11\n\targuments\x18\x03 \x03(\t\x12\x0f\n\x07timeout\x18\x04 \x01(\t\"v\n\x18VerificationResponseList\x12?\n\x0cresponseList\x18\x01 \x03(\x0b\x32).DafnyExecutorServer.VerificationResponse\x12\x19\n\x11\x65xecutionTimeInMs\x18\x02 \x01(\x04\"U\n\x14VerificationResponse\x12\x10\n\x08response\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x19\n\x11\x65xecutionTimeInMs\x18\x03 \x01(\x04\x32\xbb\x04\n\x14\x44\x61\x66nyVerifierService\x12_\n\x06Verify\x12(.DafnyExecutorServer.VerificationRequest\x1a).DafnyExecutorServer.VerificationResponse\"\x00\x12m\n\x0e\x43loneAndVerify\x12*.DafnyExecutorServer.CloneAndVerifyRequest\x1a-.DafnyExecutorServer.VerificationResponseList\"\x00\x12S\n\x0f\x43reateTmpFolder\x12\x1e.DafnyExecutorServer.CreateDir\x1a\x1e.DafnyExecutorServer.TmpFolder\"\x00\x12L\n\x0cRemoveFolder\x12\x1e.DafnyExecutorServer.TmpFolder\x1a\x1a.DafnyExecutorServer.Empty\"\x00\x12S\n\x0f\x44uplicateFolder\x12\x1e.DafnyExecutorServer.TmpFolder\x1a\x1e.DafnyExecutorServer.TmpFolder\"\x00\x12[\n\x11WriteToRemoteFile\x12(.DafnyExecutorServer.VerificationRequest\x1a\x1a.DafnyExecutorServer.Empty\"\x00\x42\x12\xaa\x02\x0fMicrosoft.Dafnyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verifier_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\017Microsoft.Dafny'
  _CREATEDIR._serialized_start=39
  _CREATEDIR._serialized_end=65
  _EMPTY._serialized_start=67
  _EMPTY._serialized_end=74
  _CLONEANDVERIFYREQUEST._serialized_start=77
  _CLONEANDVERIFYREQUEST._serialized_end=224
  _TMPFOLDER._serialized_start=226
  _TMPFOLDER._serialized_end=289
  _VERIFICATIONREQUEST._serialized_start=291
  _VERIFICATIONREQUEST._serialized_end=376
  _VERIFICATIONRESPONSELIST._serialized_start=378
  _VERIFICATIONRESPONSELIST._serialized_end=496
  _VERIFICATIONRESPONSE._serialized_start=498
  _VERIFICATIONRESPONSE._serialized_end=583
  _DAFNYVERIFIERSERVICE._serialized_start=586
  _DAFNYVERIFIERSERVICE._serialized_end=1157
# @@protoc_insertion_point(module_scope)
