# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import verifier_pb2 as verifier__pb2


class DafnyVerifierServiceStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Verify = channel.unary_unary(
                '/DafnyExecutorServer.DafnyVerifierService/Verify',
                request_serializer=verifier__pb2.VerificationRequest.SerializeToString,
                response_deserializer=verifier__pb2.VerificationResponse.FromString,
                )
        self.CloneAndVerify = channel.unary_unary(
                '/DafnyExecutorServer.DafnyVerifierService/CloneAndVerify',
                request_serializer=verifier__pb2.CloneAndVerifyRequest.SerializeToString,
                response_deserializer=verifier__pb2.VerificationResponseList.FromString,
                )
        self.TwoStageVerify = channel.unary_unary(
                '/DafnyExecutorServer.DafnyVerifierService/TwoStageVerify',
                request_serializer=verifier__pb2.TwoStageRequest.SerializeToString,
                response_deserializer=verifier__pb2.VerificationResponseList.FromString,
                )
        self.CreateTmpFolder = channel.unary_unary(
                '/DafnyExecutorServer.DafnyVerifierService/CreateTmpFolder',
                request_serializer=verifier__pb2.CreateDir.SerializeToString,
                response_deserializer=verifier__pb2.TmpFolder.FromString,
                )
        self.RemoveFolder = channel.unary_unary(
                '/DafnyExecutorServer.DafnyVerifierService/RemoveFolder',
                request_serializer=verifier__pb2.TmpFolder.SerializeToString,
                response_deserializer=verifier__pb2.Empty.FromString,
                )
        self.DuplicateFolder = channel.unary_unary(
                '/DafnyExecutorServer.DafnyVerifierService/DuplicateFolder',
                request_serializer=verifier__pb2.TmpFolder.SerializeToString,
                response_deserializer=verifier__pb2.TmpFolder.FromString,
                )
        self.WriteToRemoteFile = channel.unary_unary(
                '/DafnyExecutorServer.DafnyVerifierService/WriteToRemoteFile',
                request_serializer=verifier__pb2.VerificationRequest.SerializeToString,
                response_deserializer=verifier__pb2.Empty.FromString,
                )


class DafnyVerifierServiceServicer(object):
    """Interface exported by the server.
    """

    def Verify(self, request, context):
        """Run Dafny on the given code and returns the output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloneAndVerify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TwoStageVerify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTmpFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DuplicateFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteToRemoteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DafnyVerifierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=verifier__pb2.VerificationRequest.FromString,
                    response_serializer=verifier__pb2.VerificationResponse.SerializeToString,
            ),
            'CloneAndVerify': grpc.unary_unary_rpc_method_handler(
                    servicer.CloneAndVerify,
                    request_deserializer=verifier__pb2.CloneAndVerifyRequest.FromString,
                    response_serializer=verifier__pb2.VerificationResponseList.SerializeToString,
            ),
            'TwoStageVerify': grpc.unary_unary_rpc_method_handler(
                    servicer.TwoStageVerify,
                    request_deserializer=verifier__pb2.TwoStageRequest.FromString,
                    response_serializer=verifier__pb2.VerificationResponseList.SerializeToString,
            ),
            'CreateTmpFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTmpFolder,
                    request_deserializer=verifier__pb2.CreateDir.FromString,
                    response_serializer=verifier__pb2.TmpFolder.SerializeToString,
            ),
            'RemoveFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFolder,
                    request_deserializer=verifier__pb2.TmpFolder.FromString,
                    response_serializer=verifier__pb2.Empty.SerializeToString,
            ),
            'DuplicateFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.DuplicateFolder,
                    request_deserializer=verifier__pb2.TmpFolder.FromString,
                    response_serializer=verifier__pb2.TmpFolder.SerializeToString,
            ),
            'WriteToRemoteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteToRemoteFile,
                    request_deserializer=verifier__pb2.VerificationRequest.FromString,
                    response_serializer=verifier__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DafnyExecutorServer.DafnyVerifierService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DafnyVerifierService(object):
    """Interface exported by the server.
    """

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DafnyExecutorServer.DafnyVerifierService/Verify',
            verifier__pb2.VerificationRequest.SerializeToString,
            verifier__pb2.VerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloneAndVerify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DafnyExecutorServer.DafnyVerifierService/CloneAndVerify',
            verifier__pb2.CloneAndVerifyRequest.SerializeToString,
            verifier__pb2.VerificationResponseList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TwoStageVerify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DafnyExecutorServer.DafnyVerifierService/TwoStageVerify',
            verifier__pb2.TwoStageRequest.SerializeToString,
            verifier__pb2.VerificationResponseList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTmpFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DafnyExecutorServer.DafnyVerifierService/CreateTmpFolder',
            verifier__pb2.CreateDir.SerializeToString,
            verifier__pb2.TmpFolder.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DafnyExecutorServer.DafnyVerifierService/RemoveFolder',
            verifier__pb2.TmpFolder.SerializeToString,
            verifier__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DuplicateFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DafnyExecutorServer.DafnyVerifierService/DuplicateFolder',
            verifier__pb2.TmpFolder.SerializeToString,
            verifier__pb2.TmpFolder.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteToRemoteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DafnyExecutorServer.DafnyVerifierService/WriteToRemoteFile',
            verifier__pb2.VerificationRequest.SerializeToString,
            verifier__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
